<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMfGJNgD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMfGJNgD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMfGJNgD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMfGJNgD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMfGJNgD\App_KernelDevDebugContainer([
    'container.build_hash' => 'MfGJNgD',
    'container.build_id' => '5aa6afb3',
    'container.build_time' => 1681322019,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMfGJNgD');
